version: '3.9'
services:
  frontend:
    build: ./frontend
    platform: linux/x86_64
    container_name: app_frontend
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - 3003:3003
    platform: linux/x86_64
    restart: 'always'
    command: npm run dev
    volumes:
      - './backend/src:/app'
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      - PORTMYSQL=3002
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=TRACE_TRACK_USER
      - DB_PORT=3306
      - MONGODB_NAME=TRACE_TRACK
      - MONGODB_USER=root
      - MONGODB_PASSWORD=123456
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3003"]
      timeout: 10s
      retries: 5
  mysql:
    image: mysql:8.0.21
    container_name: mysql_db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

  mongo:
    image: mongo
    restart: always
    ports:
      - 3001:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5